// Generated by risc0-build::embed_methods() at build time.
// Exposes VERIFIER_GUEST_ELF (the compiled RISC-V binary) and
// VERIFIER_GUEST_ID (the image commitment, used to verify receipts).
include!(concat!(env!("OUT_DIR"), "/methods.rs"));
